
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleJavaSpec.js
 *
 * @nolint
 */

package com.rnmapbox.rnmbx;

import com.facebook.proguard.annotations.DoNotStrip;
import com.facebook.react.bridge.Promise;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReactContextBaseJavaModule;
import com.facebook.react.bridge.ReactMethod;
import com.facebook.react.bridge.ReactModuleWithSpec;
import com.facebook.react.bridge.ReadableMap;
import com.facebook.react.turbomodule.core.interfaces.TurboModule;
import javax.annotation.Nonnull;

public abstract class NativeRNMBXLocationModuleSpec extends ReactContextBaseJavaModule implements ReactModuleWithSpec, TurboModule {
  public static final String NAME = "RNMBXLocationModule";

  public NativeRNMBXLocationModuleSpec(ReactApplicationContext reactContext) {
    super(reactContext);
  }

  @Override
  public @Nonnull String getName() {
    return NAME;
  }

  protected final void emitOnLocationUpdate(ReadableMap value) {
    mEventEmitterCallback.invoke("onLocationUpdate", value);
  }

  @ReactMethod
  @DoNotStrip
  public abstract void start(double minDisplacement);

  @ReactMethod
  @DoNotStrip
  public abstract void stop();

  @ReactMethod
  @DoNotStrip
  public abstract void setRequestsAlwaysUse(boolean requestsAlwaysUse);

  @ReactMethod
  @DoNotStrip
  public abstract void setMinDisplacement(double minDisplacement);

  @ReactMethod
  @DoNotStrip
  public abstract void getLastKnownLocation(Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void simulateHeading(double changesPerSecond, double increment);

  @ReactMethod
  @DoNotStrip
  public abstract void setLocationEventThrottle(double throttle);
}
