/**
* This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
*
* This file should be updated after modifying `MBXMarkerViewNativeComponent.ts`.
*
* @generated by codegen project: GeneratePropsJavaInterface.js
*/

package com.facebook.react.viewmanagers;

import android.view.View;
import androidx.annotation.Nullable;
import com.facebook.react.bridge.ReadableMap;

public interface MBXMarkerViewManagerInterface<T extends View> {
  void setCoordinate(T view, @Nullable String value);
  void setAnchor(T view, @Nullable ReadableMap value);
  void setAllowOverlap(T view, boolean value);
  void setIsSelected(T view, boolean value);
}
