/**
* This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
*
* Do not edit this file as changes may cause incorrect behavior and will be lost
* once the code is regenerated.
*
* @generated by codegen project: GeneratePropsJavaInterface.js
*/

package com.facebook.react.viewmanagers;

import android.view.View;
import com.facebook.react.bridge.Dynamic;

public interface RNMBXCameraManagerInterface<T extends View> {
  void setMaxBounds(T view, Dynamic value);
  void setAnimationDuration(T view, Dynamic value);
  void setAnimationMode(T view, Dynamic value);
  void setDefaultStop(T view, Dynamic value);
  void setUserTrackingMode(T view, Dynamic value);
  void setFollowUserLocation(T view, Dynamic value);
  void setFollowUserMode(T view, Dynamic value);
  void setFollowZoomLevel(T view, Dynamic value);
  void setFollowPitch(T view, Dynamic value);
  void setFollowHeading(T view, Dynamic value);
  void setFollowPadding(T view, Dynamic value);
  void setZoomLevel(T view, Dynamic value);
  void setMaxZoomLevel(T view, Dynamic value);
  void setMinZoomLevel(T view, Dynamic value);
  void setStop(T view, Dynamic value);
}
