/**
* This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
*
* Do not edit this file as changes may cause incorrect behavior and will be lost
* once the code is regenerated.
*
* @generated by codegen project: GeneratePropsJavaInterface.js
*/

package com.facebook.react.viewmanagers;

import android.view.View;
import com.facebook.react.bridge.Dynamic;

public interface RNMBXMarkerViewManagerInterface<T extends View> {
  void setCoordinate(T view, Dynamic value);
  void setAnchor(T view, Dynamic value);
  void setAllowOverlap(T view, Dynamic value);
  void setAllowOverlapWithPuck(T view, Dynamic value);
  void setIsSelected(T view, Dynamic value);
}
