/**
* This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
*
* Do not edit this file as changes may cause incorrect behavior and will be lost
* once the code is regenerated.
*
* @generated by codegen project: GeneratePropsJavaInterface.js
*/

package com.facebook.react.viewmanagers;

import android.view.View;
import com.facebook.react.bridge.Dynamic;

public interface RNMBXShapeSourceManagerInterface<T extends View> {
  void setId(T view, Dynamic value);
  void setExisting(T view, Dynamic value);
  void setUrl(T view, Dynamic value);
  void setShape(T view, Dynamic value);
  void setCluster(T view, Dynamic value);
  void setClusterRadius(T view, Dynamic value);
  void setClusterMaxZoomLevel(T view, Dynamic value);
  void setClusterProperties(T view, Dynamic value);
  void setMaxZoomLevel(T view, Dynamic value);
  void setBuffer(T view, Dynamic value);
  void setTolerance(T view, Dynamic value);
  void setLineMetrics(T view, Dynamic value);
  void setHasPressListener(T view, Dynamic value);
  void setHitbox(T view, Dynamic value);
}
