# Configuration for Label Actions - https://github.com/dessant/label-actions

name: "Label Actions"

on:
  issues:
    types: labeled

permissions:
  contents: read
  issues: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/label-actions@v2
